name: Deploy Laravel to VPS using Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Đăng nhập vào Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t your-dockerhub-username/laravel-app:latest .

      - name: Push Docker Image lên Docker Hub
        run: docker push your-dockerhub-username/laravel-app:latest

      - name: SSH vào VPS và Pull Image mới
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull your-dockerhub-username/laravel-app:latest
            docker stop laravel_app || true
            docker rm laravel_app || true
            docker run -d --name laravel_app -p 8000:80 your-dockerhub-username/laravel-app:latest
